on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: thomascasse/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://213.190.6.92:21/domains/thomascasse.com/public_html
        ftp-username: u702285148
        ftp-password: ${{ secrets.redwood2k }}
